# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  ## the PV (PersistenceVolume) that matches the storage and uses the same storageClassName will be bound. 
  ## The Storage Class defined in the storageClassName will dynamically provision/create a PV if a matching PV cannot be found.
  ## If not storageClassName is specified, the 'standard' SC will be used by default.
  ## storageClassName: standard
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.